// Dashboard_251202_1812/src/App.tsx
import Header from './components/layout/Header';
import Footer from './components/layout/Footer';
import FilterArea from './components/features/dashboard/FilterArea';
import DataTable from './components/features/dashboard/DataTable';
import PageTabs from './components/features/dashboard/PageTabs';

function App() {
  return (
    <div className="flex flex-col h-screen">
      <Header />
      <div className="flex-1 flex flex-col bg-[#f8f9fa] overflow-hidden">
        <FilterArea />
        <DataTable />
        <PageTabs />
      </div>
      <Footer />
    </div>
  );
}

export default App;

// Dashboard_251202_1432/src/App.vue
<script setup lang="ts">
import AppHeader from './components/layout/AppHeader.vue'
import FilterArea from './components/features/FilterArea.vue'
import DataTableArea from './components/features/DataTableArea.vue'
</script>

<template>
  <v-app>
    <AppHeader />

    <v-main>
      <div class="dashboard-container">
        <FilterArea />
        <DataTableArea />
      </div>
    </v-main>

    <!-- Footer -->
    <v-footer
      height="20"
      color="#f8f9fa"
      class="footer"
    >
      <div class="footer-content"></div>
    </v-footer>
  </v-app>
</template>

<style scoped>
.dashboard-container {
  background-color: #f8f9fa;
  min-height: calc(100vh - 60px);
}

.footer {
  border-top: 1px solid #e8ecef;
}

.footer-content {
  width: 100%;
  height: 100%;
}
</style>
