// Dashboard_251202_1432/src/components/features/FilterArea.vue
<template>
  <div class="filter-area">
    <!-- Page Header -->
    <div class="page-header mb-2">
      <h1 class="page-title">동종확산 Dashboard</h1>
    </div>

    <v-divider class="mb-2"></v-divider>

    <!-- Filters -->
    <div class="d-flex align-end justify-space-between">
      <div class="d-flex align-end" style="gap: 8px;">
        <!-- Line -->
        <div class="filter-field">
          <label class="filter-label">Line<span class="required">*</span></label>
          <v-select
            v-model="filters.line"
            :items="lineItems"
            variant="outlined"
            density="compact"
            hide-details
            class="filter-select"
            style="width: 120px;"
          ></v-select>
        </div>

        <!-- Sub area -->
        <div class="filter-field">
          <label class="filter-label">Sub area</label>
          <v-select
            v-model="filters.subArea"
            :items="subAreaItems"
            variant="outlined"
            density="compact"
            hide-details
            class="filter-select"
            style="width: 120px;"
          ></v-select>
        </div>

        <!-- Design rule -->
        <div class="filter-field">
          <label class="filter-label">Design rule<span class="required">*</span></label>
          <v-select
            v-model="filters.designRule"
            :items="designRuleItems"
            variant="outlined"
            density="compact"
            hide-details
            class="filter-select"
            style="width: 120px;"
          ></v-select>
        </div>

        <!-- Process ID -->
        <div class="filter-field">
          <label class="filter-label">Process ID<span class="required">*</span></label>
          <v-select
            v-model="filters.processId"
            :items="processIdItems"
            variant="outlined"
            density="compact"
            hide-details
            class="filter-select"
            style="width: 120px;"
          ></v-select>
        </div>

        <!-- PRC group -->
        <div class="filter-field">
          <label class="filter-label">PRC group<span class="required">*</span></label>
          <v-select
            v-model="filters.prcGroup"
            :items="prcGroupItems"
            variant="outlined"
            density="compact"
            hide-details
            class="filter-select"
            style="width: 250px;"
          ></v-select>
        </div>

        <!-- Step seq -->
        <div class="filter-field">
          <label class="filter-label">Step seq</label>
          <v-select
            v-model="filters.stepSeq"
            :items="stepSeqItems"
            variant="outlined"
            density="compact"
            hide-details
            class="filter-select"
            style="width: 332px;"
          ></v-select>
        </div>
      </div>

      <!-- Action Buttons -->
      <div class="d-flex align-center" style="gap: 6px;">
        <div class="divider-vertical"></div>
        <v-btn
          color="#3392d3"
          variant="flat"
          size="small"
          class="action-btn primary-btn"
        >
          검색
        </v-btn>
        <v-btn
          variant="outlined"
          size="small"
          class="action-btn secondary-btn"
        >
          조건 저장
        </v-btn>
        <v-btn
          variant="outlined"
          size="small"
          class="action-btn secondary-btn"
        >
          조건 불러오기
        </v-btn>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const filters = ref({
  line: 'A1_ABCD',
  subArea: 'CVD',
  designRule: 'ABC12',
  processId: 'EFGH',
  prcGroup: 'AB12345CD:EFGHJKLMNOPR25',
  stepSeq: 'AB12345CD:EFGHIJKLMNOPQRSTUV123435'
})

const lineItems = ['A1_ABCD', 'A2_EFGH', 'B1_IJKL']
const subAreaItems = ['CVD', 'PVD', 'ETCH']
const designRuleItems = ['ABC12', 'DEF34', 'GHI56']
const processIdItems = ['EFGH', 'IJKL', 'MNOP']
const prcGroupItems = ['AB12345CD:EFGHJKLMNOPR25', 'XY67890ZZ:ABCDEFGHIJK12']
const stepSeqItems = ['AB12345CD:EFGHIJKLMNOPQRSTUV123435', 'CD67890EF:GHIJKLMNOPQRSTUV789012']
</script>

<style scoped>
.filter-area {
  padding: 12px;
  background-color: #ffffff;
}

.page-header {
  padding-top: 12px;
}

.page-title {
  font-family: 'SamsungOneKoreanNoF', sans-serif;
  font-weight: 700;
  font-size: 20px;
  line-height: 24px;
  letter-spacing: 0.8px;
  color: #384047;
  margin: 0;
}

.filter-field {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.filter-label {
  font-family: 'SamsungOneKoreanNoF', sans-serif;
  font-weight: 700;
  font-size: 12px;
  line-height: 20px;
  letter-spacing: 0.8px;
  color: #565e66;
}

.required {
  color: #ff4337;
}

.filter-select :deep(.v-field) {
  background-color: #ffffff;
  border-color: #dadfe4;
  font-family: 'SamsungOneKoreanNoF', sans-serif;
  font-size: 14px;
  line-height: 20px;
  letter-spacing: 0.8px;
  color: #384047;
}

.filter-select :deep(.v-field__input) {
  padding: 2px 6px;
  min-height: 24px;
}

.divider-vertical {
  width: 1px;
  height: 10px;
  background-color: #ccd1d6;
}

.action-btn {
  font-family: 'SamsungOneKoreanNoF', sans-serif;
  font-size: 14px;
  line-height: 20px;
  letter-spacing: 0.8px;
  text-transform: none;
  height: 24px;
}

.primary-btn {
  font-weight: 700;
  color: #ffffff !important;
}

.secondary-btn {
  font-weight: 400;
  color: #384047 !important;
  border-color: #dadfe4;
  background-color: #ffffff;
}
</style>

// Dashboard_251202_1812/src/components/features/dashboard/FilterArea.tsx
import { ChevronDown } from 'lucide-react';

export default function FilterArea() {
  return (
    <div className="px-3 py-3">
      {/* Page Header */}
      <div className="mb-2">
        <h1 className="text-[20px] font-bold leading-6 tracking-[0.8px] text-[#384047]">
          동종확산 Dashboard
        </h1>
      </div>

      {/* Divider */}
      <div className="h-px bg-[#dadfe4] mb-3" />

      {/* Filters */}
      <div className="flex items-end gap-2">
        {/* Filter Fields */}
        <div className="flex gap-2">
          {/* Line */}
          <div className="flex flex-col gap-0.5">
            <label className="text-xs font-bold leading-5 tracking-[0.8px] text-[#565e66]">
              Line<span className="text-[#ff4337]">*</span>
            </label>
            <div className="w-[120px] bg-white border border-[#dadfe4] rounded-sm px-1.5 py-0.5 flex items-center justify-between">
              <span className="text-sm leading-5 tracking-[0.8px] text-[#384047]">A1_ABCD</span>
              <ChevronDown className="w-4 h-4 text-[#b2b6bb]" />
            </div>
          </div>

          {/* Sub area */}
          <div className="flex flex-col gap-0.5">
            <label className="text-xs font-bold leading-5 tracking-[0.8px] text-[#565e66]">
              Sub area
            </label>
            <div className="w-[120px] bg-white border border-[#dadfe4] rounded-sm px-1.5 py-0.5 flex items-center justify-between">
              <span className="text-sm leading-5 tracking-[0.8px] text-[#384047]">CVD</span>
              <ChevronDown className="w-4 h-4 text-[#b2b6bb]" />
            </div>
          </div>

          {/* Design rule */}
          <div className="flex flex-col gap-0.5">
            <label className="text-xs font-bold leading-5 tracking-[0.8px] text-[#565e66]">
              Design rule<span className="text-[#ff4337]">*</span>
            </label>
            <div className="w-[120px] bg-white border border-[#dadfe4] rounded-sm px-1.5 py-0.5 flex items-center justify-between">
              <span className="text-sm leading-5 tracking-[0.8px] text-[#384047]">ABC12</span>
              <ChevronDown className="w-4 h-4 text-[#b2b6bb]" />
            </div>
          </div>

          {/* Process ID */}
          <div className="flex flex-col gap-0.5">
            <label className="text-xs font-bold leading-5 tracking-[0.8px] text-[#565e66]">
              Process ID<span className="text-[#ff4337]">*</span>
            </label>
            <div className="w-[120px] bg-white border border-[#dadfe4] rounded-sm px-1.5 py-0.5 flex items-center justify-between">
              <span className="text-sm leading-5 tracking-[0.8px] text-[#384047]">EFGH</span>
              <ChevronDown className="w-4 h-4 text-[#b2b6bb]" />
            </div>
          </div>

          {/* PRC group */}
          <div className="flex flex-col gap-0.5">
            <label className="text-xs font-bold leading-5 tracking-[0.8px] text-[#565e66]">
              PRC group<span className="text-[#ff4337]">*</span>
            </label>
            <div className="w-[250px] bg-white border border-[#dadfe4] rounded-sm px-1.5 py-0.5 flex items-center justify-between">
              <span className="text-sm leading-5 tracking-[0.8px] text-[#384047] truncate">
                AB12345CD:EFGHJKLMNOPR25
              </span>
              <ChevronDown className="w-4 h-4 text-[#b2b6bb] flex-shrink-0" />
            </div>
          </div>

          {/* Step seq */}
          <div className="flex flex-col gap-0.5">
            <label className="text-xs font-bold leading-5 tracking-[0.8px] text-[#565e66]">
              Step seq
            </label>
            <div className="w-[332px] bg-white border border-[#dadfe4] rounded-sm px-1.5 py-0.5 flex items-center justify-between">
              <span className="text-sm leading-5 tracking-[0.8px] text-[#384047] truncate">
                AB12345CD:EFGHIJKLMNOPQRSTUV123435
              </span>
              <ChevronDown className="w-4 h-4 text-[#b2b6bb] flex-shrink-0" />
            </div>
          </div>
        </div>

        {/* Buttons */}
        <div className="flex items-center gap-1.5 ml-3">
          <div className="h-2.5 w-px bg-[#ccd1d6]" />
          <button className="bg-[#3392d3] text-white text-sm font-bold leading-5 tracking-[0.8px] px-2 h-6 rounded-sm hover:bg-[#2d7cb8]">
            검색
          </button>
          <button className="bg-white border border-[#dadfe4] text-[#384047] text-sm leading-5 tracking-[0.8px] px-2 py-0.5 rounded-sm hover:bg-gray-50">
            조건 저장
          </button>
          <button className="bg-white border border-[#dadfe4] text-[#384047] text-sm leading-5 tracking-[0.8px] px-2 py-0.5 rounded-sm hover:bg-gray-50">
            조건 불러오기
          </button>
        </div>
      </div>
    </div>
  );
}
