// Dashboard_251229_1511_Vue/src/App.vue
<template>
  <v-app>
    <AppHeader />

    <v-main>
      <div class="dashboard-container">
        <!-- Filter Area -->
        <FilterArea />

        <!-- Page Tabs -->
        <PageTabs />

        <!-- Dashboard Table -->
        <DashboardTable />
      </div>
    </v-main>

    <AppFooter />
  </v-app>
</template>

<script setup lang="ts">
import AppHeader from './components/layout/AppHeader.vue'
import AppFooter from './components/layout/AppFooter.vue'
import FilterArea from './components/features/Dashboard/FilterArea.vue'
import PageTabs from './components/features/Dashboard/PageTabs.vue'
import DashboardTable from './components/features/Dashboard/DashboardTable.vue'
</script>

<style scoped>
.dashboard-container {
  background-color: #edf2f4;
  min-height: calc(100vh - 60px);
  padding-bottom: 20px;
}
</style>

// Dashboard_251203_1506_React/src/App.tsx
import Header from './components/layout/Header';
import Footer from './components/layout/Footer';
import FilterArea from './components/features/FilterArea';
import DataTable from './components/features/DataTable';
import PageTabs from './components/features/PageTabs';

function App() {
  return (
    <div className="flex flex-col h-screen">
      {/* Header */}
      <Header />

      {/* Main Content */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {/* Filter Area */}
        <FilterArea />

        {/* Data Table Area */}
        <DataTable />

        {/* Page Tabs */}
        <PageTabs />
      </div>

      {/* Footer */}
      <Footer />
    </div>
  );
}

export default App;
