// Dashboard_251202_1812/src/components/features/dashboard/PageTabs.tsx
import { X, ChevronLeft, ChevronRight, Menu } from 'lucide-react';

export default function PageTabs() {
  return (
    <div className="h-6 flex items-center bg-[#e4e9ed] border-t border-[#dadfe4]">
      {/* Tab 1 - Inactive */}
      <div className="flex items-stretch h-6 border-l border-[#dadfe4]">
        <div className="bg-[#e4e9ed] flex items-center px-3 gap-2 border-t border-b border-[#dadfe4]">
          <span className="text-xs leading-[14px] tracking-[0.8px] text-[#767d84]">PEMS Main</span>
          <button className="hover:bg-black/5 p-0.5 rounded">
            <X className="w-4 h-4 text-[#767d84]" />
          </button>
        </div>
      </div>

      {/* Tab 2 - Active */}
      <div className="flex items-stretch h-6 border-l border-[#dadfe4]">
        <div className="bg-white flex items-center px-3 gap-2 border-t border-b border-[#dadfe4]">
          <span className="text-xs font-bold leading-5 tracking-[0.8px] text-[#3392d3]">
            동종확산 ECO Highway
          </span>
          <button className="hover:bg-black/5 p-0.5 rounded">
            <X className="w-4 h-4 text-[#3392d3]" />
          </button>
        </div>
        <div className="w-px bg-[#dadfe4]" />
      </div>

      {/* Empty space */}
      <div className="flex-1 bg-[#e4e9ed] border-t border-b border-[#dadfe4]" />

      {/* Navigation buttons */}
      <div className="flex items-stretch h-6">
        {/* Left arrow */}
        <div className="border-l border-[#dadfe4] flex items-center">
          <div className="bg-[#e4e9ed] w-[23px] h-6 flex items-center justify-center border-t border-b border-[#dadfe4]">
            <button className="hover:bg-black/5 p-0.5 rounded">
              <ChevronLeft className="w-4 h-4 text-[#b2b6bb]" />
            </button>
          </div>
        </div>

        {/* Right arrow */}
        <div className="border-l border-[#dadfe4] flex items-center">
          <div className="bg-[#e4e9ed] w-[23px] h-6 flex items-center justify-center border-t border-b border-[#dadfe4]">
            <button className="hover:bg-black/5 p-0.5 rounded">
              <ChevronRight className="w-4 h-4 text-[#b2b6bb]" />
            </button>
          </div>
        </div>

        {/* Menu button */}
        <div className="border-l border-[#dadfe4] flex items-center">
          <div className="bg-[#e4e9ed] w-[23px] h-6 flex items-center justify-center border-t border-b border-[#dadfe4]">
            <button className="hover:bg-black/5 p-0.5 rounded">
              <Menu className="w-4 h-4 text-[#b2b6bb]" />
            </button>
          </div>
        </div>

        {/* Close button */}
        <div className="border-l border-[#dadfe4] flex items-center">
          <div className="bg-[#e4e9ed] w-[23px] h-6 flex items-center justify-center border-t border-b border-[#dadfe4]">
            <button className="hover:bg-black/5 p-0.5 rounded">
              <X className="w-4 h-4 text-[#b2b6bb]" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// Dashboard_251218_1428_Vue/src/components/features/Dashboard/PageTabs.vue
<template>
  <div class="page-tabs">
    <div class="tabs-container">
      <div class="tab active">PEMS Main</div>
      <div class="tab">동종확산 ECO High...</div>
      <div class="tab inactive"></div>
    </div>
    <div class="tab-actions">
      <v-btn icon size="x-small" variant="text">
        <v-icon size="16">mdi-chevron-left</v-icon>
      </v-btn>
      <v-btn icon size="x-small" variant="text">
        <v-icon size="16">mdi-chevron-right</v-icon>
      </v-btn>
      <v-btn icon size="x-small" variant="text">
        <v-icon size="16">mdi-menu</v-icon>
      </v-btn>
      <v-btn icon size="x-small" variant="text">
        <v-icon size="16">mdi-close</v-icon>
      </v-btn>
    </div>
  </div>
</template>

<script setup lang="ts">
</script>

<style scoped>
.page-tabs {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background: #f3f6f8;
  height: 24px;
  padding: 0 12px;
  border-bottom: 1px solid #e4e9ed;
}

.tabs-container {
  display: flex;
  gap: 0;
  flex: 1;
}

.tab {
  padding: 4px 12px;
  font-size: 12px;
  color: #565e66;
  letter-spacing: 0.8px;
  line-height: 14px;
  background: #e4e9ed;
  border-right: 1px solid #dadfe4;
  cursor: pointer;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.tab.active {
  background: white;
  color: #283037;
  font-weight: 700;
}

.tab.inactive {
  flex: 1;
  background: #f3f6f8;
  border: none;
}

.tab:hover:not(.inactive) {
  background: #f0f0f0;
}

.tab-actions {
  display: flex;
  gap: 2px;
  align-items: center;
}

:deep(.v-btn) {
  color: #565e66;
}
</style>
