// Dashboard_251202_1812/src/App.tsx
import Header from './components/layout/Header';
import Footer from './components/layout/Footer';
import FilterArea from './components/features/dashboard/FilterArea';
import DataTable from './components/features/dashboard/DataTable';
import PageTabs from './components/features/dashboard/PageTabs';

function App() {
  return (
    <div className="flex flex-col h-screen">
      <Header />
      <div className="flex-1 flex flex-col bg-[#f8f9fa] overflow-hidden">
        <FilterArea />
        <DataTable />
        <PageTabs />
      </div>
      <Footer />
    </div>
  );
}

export default App;

// Dashboard_251218_1428_Vue/src/App.vue
<script setup lang="ts">
import AppHeader from './components/layout/AppHeader.vue'
import AppFooter from './components/layout/AppFooter.vue'
import FilterArea from './components/features/Dashboard/FilterArea.vue'
import DataTableToolbar from './components/features/Dashboard/DataTableToolbar.vue'
import DashboardTable from './components/features/Dashboard/DashboardTable.vue'
import PageTabs from './components/features/Dashboard/PageTabs.vue'
</script>

<template>
  <v-app>
    <AppHeader />

    <v-main class="pa-0 ma-0">
      <FilterArea />
      <DataTableToolbar />
      <DashboardTable />
      <PageTabs />
    </v-main>

    <AppFooter />
  </v-app>
</template>

<style scoped>
:deep(.v-main) {
  padding: 0 !important;
  margin: 0 !important;
}
</style>
