// Dashboard_251203_1506_React/src/components/features/FilterArea.tsx
import { ChevronDown, ChevronUp } from 'lucide-react';
import { useState } from 'react';

export default function FilterArea() {
  const [isCollapsed, setIsCollapsed] = useState(false);

  return (
    <div className="bg-white px-3 py-3">
      {/* Page Header */}
      <div className="mb-2">
        <h2 className="text-[#384047] text-xl font-bold leading-6 tracking-[0.8px]">
          동종확산 Dashboard
        </h2>
      </div>

      {/* Divider */}
      <div className="h-px bg-[#e4e9ed] mb-2" />

      {/* Filters */}
      {!isCollapsed && (
        <div className="flex items-end gap-2 mb-3">
          {/* Filter Fields */}
          <div className="flex gap-2 flex-1">
            {/* Line Filter */}
            <div className="flex flex-col gap-0.5">
              <label className="text-[#565e66] text-xs font-bold leading-5 tracking-[0.8px]">
                Line<span className="text-[#ff4337]">*</span>
              </label>
              <div className="min-w-[120px] max-w-[160px]">
                <select className="w-full px-1.5 py-0.5 border border-[#dadfe4] rounded-sm text-sm leading-5 tracking-[0.8px] text-[#384047] bg-white">
                  <option>A1_ABCD</option>
                </select>
              </div>
            </div>

            {/* Sub area Filter */}
            <div className="flex flex-col gap-0.5">
              <label className="text-[#565e66] text-xs font-bold leading-5 tracking-[0.8px]">
                Sub area
              </label>
              <div className="min-w-[120px] max-w-[160px]">
                <select className="w-full px-1.5 py-0.5 border border-[#dadfe4] rounded-sm text-sm leading-5 tracking-[0.8px] text-[#384047] bg-white">
                  <option>CVD</option>
                </select>
              </div>
            </div>

            {/* Design rule Filter */}
            <div className="flex flex-col gap-0.5">
              <label className="text-[#565e66] text-xs font-bold leading-5 tracking-[0.8px]">
                Design rule<span className="text-[#ff4337]">*</span>
              </label>
              <div className="min-w-[120px] max-w-[160px]">
                <select className="w-full px-1.5 py-0.5 border border-[#dadfe4] rounded-sm text-sm leading-5 tracking-[0.8px] text-[#384047] bg-white">
                  <option>ABC12</option>
                </select>
              </div>
            </div>

            {/* Process ID Filter */}
            <div className="flex flex-col gap-0.5">
              <label className="text-[#565e66] text-xs font-bold leading-5 tracking-[0.8px]">
                Process ID<span className="text-[#ff4337]">*</span>
              </label>
              <div className="min-w-[120px] max-w-[160px]">
                <select className="w-full px-1.5 py-0.5 border border-[#dadfe4] rounded-sm text-sm leading-5 tracking-[0.8px] text-[#384047] bg-white">
                  <option>EFGH</option>
                </select>
              </div>
            </div>

            {/* PRC group Filter */}
            <div className="flex flex-col gap-0.5">
              <label className="text-[#565e66] text-xs font-bold leading-5 tracking-[0.8px]">
                PRC group<span className="text-[#ff4337]">*</span>
              </label>
              <div className="w-[250px]">
                <select className="w-full px-1.5 py-0.5 border border-[#dadfe4] rounded-sm text-sm leading-5 tracking-[0.8px] text-[#384047] bg-white">
                  <option>AB12345CD:EFGHJKLMNOPR25</option>
                </select>
              </div>
            </div>

            {/* Step seq Filter */}
            <div className="flex flex-col gap-0.5">
              <label className="text-[#565e66] text-xs font-bold leading-5 tracking-[0.8px]">
                Step seq
              </label>
              <div className="w-[332px]">
                <select className="w-full px-1.5 py-0.5 border border-[#dadfe4] rounded-sm text-sm leading-5 tracking-[0.8px] text-[#384047] bg-white">
                  <option>AB12345CD:EFGHIJKLMNOPQRSTUV123435</option>
                </select>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center gap-1.5 ml-auto">
            <div className="h-2.5 w-px bg-[#ccd1d6]" />
            <button className="px-2 py-0.5 bg-[#3392d3] text-white text-sm font-bold leading-5 tracking-[0.8px] rounded-sm hover:bg-[#2d7db8] transition-colors">
              검색
            </button>
            <button className="px-2 py-0.5 bg-white border border-[#dadfe4] text-[#384047] text-sm leading-5 tracking-[0.8px] rounded-sm hover:bg-gray-50 transition-colors">
              조건 저장
            </button>
            <button className="px-2 py-0.5 bg-white border border-[#dadfe4] text-[#384047] text-sm leading-5 tracking-[0.8px] rounded-sm hover:bg-gray-50 transition-colors">
              조건 불러오기
            </button>
          </div>
        </div>
      )}

      {/* Collapse Button */}
      <div className="flex justify-center">
        <button
          onClick={() => setIsCollapsed(!isCollapsed)}
          className="flex items-center gap-1 px-2 py-0.5 hover:bg-gray-100 rounded-sm transition-colors"
        >
          <div className="h-px w-14 bg-[#ccd1d6]" />
          {isCollapsed ? (
            <ChevronDown className="w-3 h-3 text-[#565e66]" />
          ) : (
            <ChevronUp className="w-3 h-3 text-[#565e66]" />
          )}
          <div className="h-px w-14 bg-[#ccd1d6]" />
        </button>
      </div>
    </div>
  );
}

// Dashboard_251202_1432/src/components/features/FilterArea.vue
<template>
  <div class="filter-area">
    <!-- Page Header -->
    <div class="page-header mb-2">
      <h1 class="page-title">동종확산 Dashboard</h1>
    </div>

    <v-divider class="mb-2"></v-divider>

    <!-- Filters -->
    <div class="d-flex align-end justify-space-between">
      <div class="d-flex align-end" style="gap: 8px;">
        <!-- Line -->
        <div class="filter-field">
          <label class="filter-label">Line<span class="required">*</span></label>
          <v-select
            v-model="filters.line"
            :items="lineItems"
            variant="outlined"
            density="compact"
            hide-details
            class="filter-select"
            style="width: 120px;"
          ></v-select>
        </div>

        <!-- Sub area -->
        <div class="filter-field">
          <label class="filter-label">Sub area</label>
          <v-select
            v-model="filters.subArea"
            :items="subAreaItems"
            variant="outlined"
            density="compact"
            hide-details
            class="filter-select"
            style="width: 120px;"
          ></v-select>
        </div>

        <!-- Design rule -->
        <div class="filter-field">
          <label class="filter-label">Design rule<span class="required">*</span></label>
          <v-select
            v-model="filters.designRule"
            :items="designRuleItems"
            variant="outlined"
            density="compact"
            hide-details
            class="filter-select"
            style="width: 120px;"
          ></v-select>
        </div>

        <!-- Process ID -->
        <div class="filter-field">
          <label class="filter-label">Process ID<span class="required">*</span></label>
          <v-select
            v-model="filters.processId"
            :items="processIdItems"
            variant="outlined"
            density="compact"
            hide-details
            class="filter-select"
            style="width: 120px;"
          ></v-select>
        </div>

        <!-- PRC group -->
        <div class="filter-field">
          <label class="filter-label">PRC group<span class="required">*</span></label>
          <v-select
            v-model="filters.prcGroup"
            :items="prcGroupItems"
            variant="outlined"
            density="compact"
            hide-details
            class="filter-select"
            style="width: 250px;"
          ></v-select>
        </div>

        <!-- Step seq -->
        <div class="filter-field">
          <label class="filter-label">Step seq</label>
          <v-select
            v-model="filters.stepSeq"
            :items="stepSeqItems"
            variant="outlined"
            density="compact"
            hide-details
            class="filter-select"
            style="width: 332px;"
          ></v-select>
        </div>
      </div>

      <!-- Action Buttons -->
      <div class="d-flex align-center" style="gap: 6px;">
        <div class="divider-vertical"></div>
        <v-btn
          color="#3392d3"
          variant="flat"
          size="small"
          class="action-btn primary-btn"
        >
          검색
        </v-btn>
        <v-btn
          variant="outlined"
          size="small"
          class="action-btn secondary-btn"
        >
          조건 저장
        </v-btn>
        <v-btn
          variant="outlined"
          size="small"
          class="action-btn secondary-btn"
        >
          조건 불러오기
        </v-btn>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const filters = ref({
  line: 'A1_ABCD',
  subArea: 'CVD',
  designRule: 'ABC12',
  processId: 'EFGH',
  prcGroup: 'AB12345CD:EFGHJKLMNOPR25',
  stepSeq: 'AB12345CD:EFGHIJKLMNOPQRSTUV123435'
})

const lineItems = ['A1_ABCD', 'A2_EFGH', 'B1_IJKL']
const subAreaItems = ['CVD', 'PVD', 'ETCH']
const designRuleItems = ['ABC12', 'DEF34', 'GHI56']
const processIdItems = ['EFGH', 'IJKL', 'MNOP']
const prcGroupItems = ['AB12345CD:EFGHJKLMNOPR25', 'XY67890ZZ:ABCDEFGHIJK12']
const stepSeqItems = ['AB12345CD:EFGHIJKLMNOPQRSTUV123435', 'CD67890EF:GHIJKLMNOPQRSTUV789012']
</script>

<style scoped>
.filter-area {
  padding: 12px;
  background-color: #ffffff;
}

.page-header {
  padding-top: 12px;
}

.page-title {
  font-family: 'SamsungOneKoreanNoF', sans-serif;
  font-weight: 700;
  font-size: 20px;
  line-height: 24px;
  letter-spacing: 0.8px;
  color: #384047;
  margin: 0;
}

.filter-field {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.filter-label {
  font-family: 'SamsungOneKoreanNoF', sans-serif;
  font-weight: 700;
  font-size: 12px;
  line-height: 20px;
  letter-spacing: 0.8px;
  color: #565e66;
}

.required {
  color: #ff4337;
}

.filter-select :deep(.v-field) {
  background-color: #ffffff;
  border-color: #dadfe4;
  font-family: 'SamsungOneKoreanNoF', sans-serif;
  font-size: 14px;
  line-height: 20px;
  letter-spacing: 0.8px;
  color: #384047;
}

.filter-select :deep(.v-field__input) {
  padding: 2px 6px;
  min-height: 24px;
}

.divider-vertical {
  width: 1px;
  height: 10px;
  background-color: #ccd1d6;
}

.action-btn {
  font-family: 'SamsungOneKoreanNoF', sans-serif;
  font-size: 14px;
  line-height: 20px;
  letter-spacing: 0.8px;
  text-transform: none;
  height: 24px;
}

.primary-btn {
  font-weight: 700;
  color: #ffffff !important;
}

.secondary-btn {
  font-weight: 400;
  color: #384047 !important;
  border-color: #dadfe4;
  background-color: #ffffff;
}
</style>
