// Dashboard_251218_1549_Vue/src/components/features/Dashboard/PageTabs.vue
<template>
  <div class="page-tabs">
    <!-- Tab 1: PEMS Main -->
    <div class="tab-item inactive">
      <div class="tab-border-top"></div>
      <div class="tab-content">
        <span class="tab-text">PEMS Main</span>
      </div>
      <div class="tab-border-bottom"></div>
    </div>

    <!-- Tab 2: 동종확산 ECO Highway (Active) -->
    <div class="tab-item active">
      <div class="tab-border-top active"></div>
      <div class="tab-content active">
        <span class="tab-text active">동종확산 ECO Highway</span>
      </div>
      <div class="tab-border-bottom"></div>
      <div class="tab-border-right"></div>
    </div>

    <!-- Empty Area -->
    <div class="tab-empty">
      <div class="tab-border-top"></div>
      <div class="empty-content"></div>
      <div class="tab-border-bottom"></div>
    </div>

    <!-- Navigation Buttons -->
    <div class="tab-nav-btn">
      <div class="tab-border-top"></div>
      <div class="nav-btn-content">
        <v-btn icon size="x-small" variant="text">
          <v-icon size="14" color="#b2b6bb">mdi-chevron-left</v-icon>
        </v-btn>
      </div>
      <div class="tab-border-bottom"></div>
    </div>

    <div class="tab-nav-btn">
      <div class="tab-border-top"></div>
      <div class="nav-btn-content">
        <v-btn icon size="x-small" variant="text">
          <v-icon size="14" color="#b2b6bb">mdi-chevron-right</v-icon>
        </v-btn>
      </div>
      <div class="tab-border-bottom"></div>
    </div>

    <div class="tab-nav-btn">
      <div class="tab-border-top"></div>
      <div class="nav-btn-content">
        <v-btn icon size="x-small" variant="text">
          <v-icon size="14" color="#767d84">mdi-dots-horizontal</v-icon>
        </v-btn>
      </div>
      <div class="tab-border-bottom"></div>
    </div>

    <div class="tab-nav-btn">
      <div class="tab-border-top"></div>
      <div class="nav-btn-content">
        <v-btn icon size="x-small" variant="text">
          <v-icon size="14" color="#767d84">mdi-close</v-icon>
        </v-btn>
      </div>
      <div class="tab-border-bottom"></div>
    </div>
  </div>
</template>

<script setup lang="ts">
</script>

<style scoped>
.page-tabs {
  display: flex;
  align-items: stretch;
  height: 24px;
  background-color: #e4e9ed;
}

.tab-item {
  display: flex;
  flex-direction: column;
  min-width: 120px;
  max-width: 200px;
  border-left: 1px solid #dadfe4;
}

.tab-item.inactive {
  background-color: #e4e9ed;
}

.tab-item.active {
  background-color: white;
}

.tab-border-top {
  height: 1px;
  background-color: #dadfe4;
}

.tab-border-top.active {
  background-color: #e4e9ed;
}

.tab-border-bottom {
  height: 1px;
  background-color: #dadfe4;
}

.tab-border-right {
  position: absolute;
  right: 0;
  top: 0;
  bottom: 0;
  width: 1px;
  background-color: #dadfe4;
}

.tab-content {
  flex: 1;
  display: flex;
  align-items: center;
  padding: 1px 11px 1px 11px;
  gap: 8px;
}

.tab-content.active {
  background-color: white;
}

.tab-text {
  font-family: 'SamsungOneKoreanNoF', sans-serif;
  font-size: 12px;
  font-weight: 400;
  line-height: 14px;
  letter-spacing: 0.8px;
  color: #767d84;
  flex: 1;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.tab-text.active {
  font-weight: 700;
  color: #3392d3;
}

.tab-empty {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-width: 3px;
}

.empty-content {
  flex: 1;
  background-color: #e4e9ed;
}

.tab-nav-btn {
  display: flex;
  flex-direction: column;
  width: 22px;
  border-left: 1px solid #dadfe4;
}

.nav-btn-content {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1px;
  background-color: #e4e9ed;
}

:deep(.v-btn) {
  min-width: 16px;
  min-height: 16px;
  width: 16px;
  height: 16px;
  padding: 2px;
}
</style>

// Dashboard_251202_1432/src/components/features/PageTabs.tsx
export default function PageTabs() {
  return (
    <div className="flex items-center h-6 px-3">
      <div className="flex items-center w-[160px] min-w-[120px] max-w-[200px]">
        <div className="bg-[#dadfe4] h-6 w-px" />
        <div className="flex flex-1 flex-col items-start">
          <div className="bg-[#dadfe4] h-px w-full" />
          <div className="bg-[#e4e9ed] flex gap-2 items-center pl-[11px] pr-[3px] py-px w-full">
            <p className="flex-1 text-[#767d84] text-[12px] leading-[14px] tracking-[0.8px] whitespace-nowrap overflow-hidden text-ellipsis">
              PEMS Main
            </p>
            <div className="bg-transparent flex items-start rounded-[2px]">
              <div className="flex gap-1 items-center p-0.5">
                <div className="rounded-[2px] w-4 h-4" />
              </div>
            </div>
          </div>
          <div className="bg-[#dadfe4] h-px w-full" />
        </div>
      </div>

      <div className="flex items-center w-[170px] min-w-[120px] max-w-[200px]">
        <div className="bg-[#dadfe4] h-6 w-px" />
        <div className="flex flex-1 flex-col items-start">
          <div className="bg-[#e4e9ed] h-px w-full" />
          <div className="bg-white flex gap-2 items-center pl-[11px] pr-[3px] py-px w-full">
            <p className="flex-1 text-[#3392d3] text-[12px] font-bold leading-5 tracking-[0.8px] whitespace-nowrap overflow-hidden text-ellipsis">
              동종확산 ECO Highway
            </p>
            <div className="bg-transparent flex items-start rounded-[2px]">
              <div className="flex gap-1 items-center p-0.5">
                <div className="rounded-[2px] w-4 h-4" />
              </div>
            </div>
          </div>
          <div className="bg-[#dadfe4] h-px w-full" />
        </div>
        <div className="bg-[#dadfe4] h-6 w-px" />
      </div>

      <div className="flex flex-1 items-center min-w-[3px]">
        <div className="flex flex-1 flex-col items-start">
          <div className="bg-[#dadfe4] h-px w-full" />
          <div className="bg-[#e4e9ed] h-[22px] w-full" />
          <div className="bg-[#dadfe4] h-px w-full" />
        </div>
      </div>

      <div className="flex items-center">
        <div className="bg-[#dadfe4] h-6 w-px" />
        <div className="flex flex-col items-start w-[22px]">
          <div className="bg-[#dadfe4] h-px w-[22px]" />
          <div className="bg-[#e4e9ed] flex gap-2 items-center p-px w-[22px]">
            <div className="bg-transparent flex items-start rounded-[2px]">
              <div className="flex gap-1 items-center p-0.5">
                <div className="rounded-[2px] w-4 h-4 flex items-center justify-center">
                  <span className="text-[#b2b6bb] text-xs">‹</span>
                </div>
              </div>
            </div>
          </div>
          <div className="bg-[#dadfe4] h-px w-[22px]" />
        </div>
      </div>

      <div className="flex items-center">
        <div className="bg-[#dadfe4] h-6 w-px" />
        <div className="flex flex-col items-start w-[22px]">
          <div className="bg-[#dadfe4] h-px w-[22px]" />
          <div className="bg-[#e4e9ed] flex gap-2 items-center p-px w-[22px]">
            <div className="bg-transparent flex items-start rounded-[2px]">
              <div className="flex gap-1 items-center p-0.5">
                <div className="rounded-[2px] w-4 h-4 flex items-center justify-center">
                  <span className="text-[#b2b6bb] text-xs">›</span>
                </div>
              </div>
            </div>
          </div>
          <div className="bg-[#dadfe4] h-px w-[22px]" />
        </div>
      </div>

      <div className="flex items-center">
        <div className="bg-[#dadfe4] h-6 w-px" />
        <div className="flex flex-col items-start w-[22px]">
          <div className="bg-[#dadfe4] h-px w-[22px]" />
          <div className="bg-[#e4e9ed] flex gap-2 items-center p-px w-[22px]">
            <div className="bg-transparent flex items-start rounded-[2px]">
              <div className="flex gap-1 items-center p-0.5">
                <div className="rounded-[2px] w-4 h-4" />
              </div>
            </div>
          </div>
          <div className="bg-[#dadfe4] h-px w-[22px]" />
        </div>
      </div>

      <div className="flex items-center">
        <div className="bg-[#dadfe4] h-6 w-px" />
        <div className="flex flex-col items-start w-[22px]">
          <div className="bg-[#dadfe4] h-px w-[22px]" />
          <div className="bg-[#e4e9ed] flex gap-2 items-center p-px w-[22px]">
            <div className="bg-transparent flex items-start rounded-[2px]">
              <div className="flex gap-1 items-center p-0.5">
                <div className="rounded-[2px] w-4 h-4" />
              </div>
            </div>
          </div>
          <div className="bg-[#dadfe4] h-px w-[22px]" />
        </div>
      </div>
    </div>
  );
}
